export * from './lib/ngx-page-object';
export {
  $,
  $$,
  blur,
  click,
  getInt,
  getFloat,
  getValue,
  isChecked,
  isDisplayed,
  isValid,
  keyUp,
  normalizedTextContent,
  normalizedTextContents,
  normalizeText,
  setValue,
  textContent,
  textContents,
  waitToAppear,
  waitToDisappear,
  HTMLElementOrNot,
} from '@ts-page-objects/core';
