export {
  $,
  $$,
  blur,
  click,
  getNumber,
  getValue,
  isChecked,
  isDisplayed,
  isValid,
  keyUp,
  normalizedTextContent,
  normalizedTextContents,
  normalizeText,
  setValue,
  textContent,
  textContents,
  waitToAppear,
  waitToDisappear,
  HTMLElementOrNot,
  PageObject,
} from '@ts-page-objects/core';
